### ISSUE TITLE
MDP-905 connection

### ISSUE THREAD

**Issue by Kabron287** [ElluIFX/MDP-P906-Controller#1]
Hi there!
Wonderfull GUI.
I tryed to connect with P905 with the following settings:
![settings](https://github.com/user-attachments/assets/2f6fe957-a271-4ec0-b338-1f9370032c2b)
I do see received RF stream while connecting on serial port:
![Stream](https://github.com/user-attachments/assets/265ca696-cad1-44b2-8fde-adf35e8fd16c)

But connection did not established.
**AutoMatch** finds nothing.

What did I miss? I do not think that the protocol is different.

**Comment by Kabron287** [comment]
Initial connect dialog looks like:
![Stream2](https://github.com/user-attachments/assets/58bd5dd0-8d53-4dac-9766-8d3ddd400a92)

**Comment by ElluIFX** [comment]
In fact, these data streams are the custom protocol used between the host computer and the RF adapter I have coded, which only indicates that the adapter is normally connected to the host computer, but does not mean that a data connection has been established between the adapter and the P905

Additionally, I noticed that you filled in ID aa66 in the P906 sub-item, which is incorrect. If P905 supports automatic pairing (I'm not sure about this), you can click the pairing button next to it after enabling this feature to obtain the ID. If not, you can enter it manually, and it should look like this:
![image](https://github.com/user-attachments/assets/5953f64b-0832-42fc-97d9-6bf8fce706c6)
![image](https://github.com/user-attachments/assets/0acfba3b-d03c-459d-8797-ba3a8056d06e)
Both match each other.

In addition, the transmitter addresses should also match each other:
![image](https://github.com/user-attachments/assets/9caa3cf9-1f2d-4fe1-8cb1-30e9ef9d84e8)
![image](https://github.com/user-attachments/assets/606a009f-4571-4046-af25-a85a237098c6)
If you are unable to use auto-pairing, connecting the P905 to a computer and then manually modifying the configuration file should be an optional fallback.

**Comment by ElluIFX** [comment]
If the action above is established normally but communication still cannot be carried out, it may be that Miniware has destructively modified the protocol when upgrading from P905 to P906. I am unable to fix this, but I believe it is low-probability because the significant differences between the two only exist in the output power.

**Comment by ElluIFX** [comment]
In addition, I suggest you modify the channel and try again. According to my tests, a slight modification of the channel within the crowded 2.4Ghz band may greatly improve wireless performance.

**Comment by ElluIFX** [comment]
I just released a new version of the software. In this version, if you set the environment variable "MDP_ENABLE_LOG" to "1", the software will create a log file. Perform some operations, and then send the log file to me. I might be able to help you find the key.

**Comment by Kabron287** [comment]
Thanks!
Allmost success.
After I entered correct ID connection established:
green LED blink and Wheel changed color. 
But after some time connection brakes.
 
[mdp.log](https://github.com/user-attachments/files/16739402/mdp.log)
![Dialod](https://github.com/user-attachments/assets/21f66b2c-5bca-49ec-a8c2-0f5812994425)

**Comment by ElluIFX** [comment]
It seems it's beacause a assertion bit specified for P906 in my code, I modified it and built a new software for test, try it again.

[release](https://github.com/ElluIFX/MDP-P906-Controller/releases/tag/test)

**Comment by Kabron287** [comment]
Bingo! You Great!
Some not stable output button operation:
need to change Voltage to force ON/OFF output.
What is the function of checkbox near State label?
Also a warning occured.
![Work](https://github.com/user-attachments/assets/d1b3fcb2-a19a-4bd5-8220-c0e6256274d9)
![Warn](https://github.com/user-attachments/assets/c0af62d4-c393-4766-a192-09408cb9d19a)

[mdp.log](https://github.com/user-attachments/files/16739808/mdp.log)

**Comment by ElluIFX** [comment]
Firstly, regarding that error message, I'm not sure of its cause, it might be due to administrator privileges or an old program not being fully cleaned up, etc. This part is handled by the Python packaging program, and I can't solve it, but I can confirm that it's not a big deal, just keep going.

Secondly, regarding this error, it originates from a message identifier that I never seem before; I can only attempt to associate it with known identifiers. I am not sure if this will solve the problem; further testing is needed on your part.

Regarding that checkbox, it is the "Quick Set" feature. If you do not check it, when modifying voltage or current, you need to let the SpinBox lose focus or press Enter to submit the changes; but if you check it, your changes will be submitted in real-time: This is a very useful little feature.

[New version](https://github.com/ElluIFX/MDP-P906-Controller/releases/tag/test)

**Comment by ElluIFX** [comment]
Also, I noticed that it seems you haven't installed the font I'm using, because it looks like you're using the default Microsoft font, of course, this isn't a big deal :)

**Comment by Kabron287** [comment]
Now works fine.
You did not mentioned any font

**Comment by ElluIFX** [comment]
> Now works fine. You did not mentioned any font

The interface font uses Sarasa. Remember to install one in the [Microsoft Store](https://www.microsoft.com/store/productId/9MW0M424NCZ7?ocid=pdpshare)

Glad to see it works

**Comment by Kabron287** [comment]
Installed Sarasa. No differences.
![Compare](https://github.com/user-attachments/assets/331e55ec-2e4e-433a-a1df-2aea788f0b32)

**Comment by ElluIFX** [comment]
Well, Windows font management is a huge mess. Considering you're using RU language, I'm not sure where the problem is, maybe it will automatically apply one day.

What's more, I just fixed two bugs, see release for the latest version.
